In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk

In [3]:
df =pd.read_csv('spam.csv',encoding='latin1')

In [4]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
df = df[['v2', 'v1']]
df = df.rename(columns={'v2': 'messages', 'v1': 'label'})
df.head()

                                            messages label
0  Go until jurong point, crazy.. Available only ...   ham
1                      Ok lar... Joking wif u oni...   ham
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam
3  U dun say so early hor... U c already then say...   ham
4  Nah I don't think he goes to usf, he lives aro...   ham

In [6]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'<.*?>', ' ', text)
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [7]:
df['messages']= df['messages'].apply(clean_text)

In [8]:
import string
def remove_punc(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [9]:
df['messages']= df['messages'].apply(remove_punc)

In [10]:
df

                                               messages label
0     go until jurong point crazy available only in ...   ham
1                               ok lar joking wif u oni   ham
2     free entry in 2 a wkly comp to win fa cup fina...  spam
3           u dun say so early hor u c already then say   ham
4     nah i dont think he goes to usf he lives aroun...   ham
...                                                 ...   ...
5567  this is the 2nd time we have tried 2 contact u...  spam
5568                will ì b going to esplanade fr home   ham
5569  pity  was in mood for that soany other suggest...   ham
5570  the guy did some bitching but i acted like id ...   ham
5571                          rofl its true to its name   ham

[5572 rows x 2 columns]

In [11]:
chat_words = {
    "a3": "anytime anywhere anyplace",
    "adih": "another day in hell",
    "afk": "away from keyboard",
    "afaik": "as far as i know",
    "asap": "as soon as possible",
    "asl": "age sex location",
    "atk": "at the keyboard",
    "atm": "at the moment",
    "bae": "before anyone else",
    "bak": "back at keyboard",
    "bbl": "be back later",
    "bbs": "be back soon",
    "bfn": "bye for now",
    "b4n": "bye for now",
    "brb": "be right back",
    "bruh": "bro",
    "brt": "be right there",
    "bsaaw": "big smile and a wink",
    "btw": "by the way",
    "bwl": "bursting with laughter",
    "csl": "cant stop laughing",
    "cu": "see you",
    "cul8r": "see you later",
    "cya": "see you",
    "dm": "direct message",
    "faq": "frequently asked questions",
    "fc": "fingers crossed",
    "fimh": "forever in my heart",
    "fomo": "fear of missing out",
    "fr": "for real",
    "fwiw": "for what its worth",
    "fyp": "for you page",
    "fyi": "for your information",
    "g9": "genius",
    "gal": "get a life",
    "gg": "good game",
    "gmta": "great minds think alike",
    "gn": "good night",
    "goat": "greatest of all time",
    "gr8": "great",
    "hbd": "happy birthday",
    "ic": "i see",
    "icq": "i seek you",
    "idc": "i do not care",
    "idk": "i do not know",
    "ifyp": "i feel your pain",
    "ilu": "i love you",
    "ily": "i love you",
    "imho": "in my honest humble opinion",
    "imu": "i miss you",
    "imo": "in my opinion",
    "iow": "in other words",
    "irl": "in real life",
    "iykyk": "if you know you know",
    "jk": "just kidding",
    "kiss": "keep it simple stupid",
    "l": "loss",
    "l8r": "later",
    "ldr": "long distance relationship",
    "lmk": "let me know",
    "lmao": "laughing my ass off",
    "lol": "laughing out loud",
    "ltns": "long time no see",
    "m8": "mate",
    "mfw": "my face when",
    "mid": "mediocre",
    "mrw": "my reaction when",
    "mte": "my thoughts exactly",
    "nvm": "never mind",
    "nrn": "no reply necessary",
    "npc": "non player character",
    "oic": "oh i see",
    "op": "overpowered",
    "pita": "pain in the ass",
    "pov": "point of view",
    "prt": "party",
    "prw": "parents are watching",
    "rofl": "rolling on the floor laughing",
    "roflol": "rolling on the floor laughing out loud",
    "rotflmao": "rolling on the floor laughing my ass off",
    "rn": "right now",
    "sk8": "skate",
    "stats": "your sex and age",
    "sus": "suspicious",
    "tbh": "to be honest",
    "tfw": "that feeling when",
    "thx": "thank you",
    "time": "tears in my eyes",
    "tldr": "too long didnt read",
    "tntl": "trying not to laugh",
    "ttfn": "ta ta for now",
    "ttyl": "talk to you later",
    "u": "you",
    "u2": "you too",
    "u4e": "yours for ever",
    "w": "win",
    "w8": "wait",
    "wb": "welcome back",
    "wtf": "what the fuck",
    "wtg": "way to go",
    "wuf": "where are you from",
    "wyd": "what you doing",
    "wywh": "wish you were here",
    "zzz": "sleeping bored tired"
}
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w in chat_words:
            new_text.append(chat_words[w])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [12]:
df['messages']= df['messages'].apply(chat_conversion)

In [13]:
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    new_text = []
    for w in text.split():
        if w not in stop_words:
            new_text.append(w)
    return " ".join(new_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nakul\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [14]:
df['messages']= df['messages'].apply(remove_stopwords)

In [15]:
df

                                               messages label
0     go jurong point crazy available bugis n great ...   ham
1                                 ok lar joking wif oni   ham
2     free entry 2 wkly comp win fa cup final tkts 2...  spam
3                       dun say early hor c already say   ham
4           nah dont think goes usf lives around though   ham
...                                                 ...   ...
5567  2nd tears eyes tried 2 contact å£750 pound pri...  spam
5568                      ì b going esplanade real home   ham
5569                        pity mood soany suggestions   ham
5570  guy bitching acted like id interested buying s...   ham
5571                   rolling floor laughing true name   ham

[5572 rows x 2 columns]

In [16]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
def stemming(text):
    stemmed_words=[]
    for w in text.split():
        stemmed_words.append(ps.stem(w))
    return " ".join(stemmed_words)

In [17]:
df['messages']= df['messages'].apply(stemming)

In [18]:
df

                                               messages label
0     go jurong point crazi avail bugi n great world...   ham
1                                   ok lar joke wif oni   ham
2     free entri 2 wkli comp win fa cup final tkt 21...  spam
3                       dun say earli hor c alreadi say   ham
4             nah dont think goe usf live around though   ham
...                                                 ...   ...
5567  2nd tear eye tri 2 contact å£750 pound prize 2...  spam
5568                          ì b go esplanad real home   ham
5569                            piti mood soani suggest   ham
5570  guy bitch act like id interest buy someth els ...   ham
5571                         roll floor laugh true name   ham

[5572 rows x 2 columns]

In [19]:
X=df['messages']
y=df['label']

In [20]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
bow = CountVectorizer(ngram_range=(1,2))
X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

model = LogisticRegression()
model.fit(X_train_bow,y_train)
y_pred= model.predict(X_test_bow)

In [22]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9775784753363229

Classification Report:
               precision    recall  f1-score   support

         ham       0.97      1.00      0.99       965
        spam       1.00      0.83      0.91       150

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115


Confusion Matrix:
 [[965   0]
 [ 25 125]]

In [23]:
model2 = MultinomialNB()
model2.fit(X_train_bow,y_train)
y_pred= model2.predict(X_test_bow)

In [24]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9820627802690582

Classification Report:
               precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       0.98      0.89      0.93       150

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115


Confusion Matrix:
 [[962   3]
 [ 17 133]]

In [25]:
model3 = SVC(C=3)
model3.fit(X_train_bow,y_train)
y_pred= model3.predict(X_test_bow)

In [26]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9748878923766816

Classification Report:
               precision    recall  f1-score   support

         ham       0.97      1.00      0.99       965
        spam       1.00      0.81      0.90       150

    accuracy                           0.97      1115
   macro avg       0.99      0.91      0.94      1115
weighted avg       0.98      0.97      0.97      1115


Confusion Matrix:
 [[965   0]
 [ 28 122]]

In [27]:
model4 = RandomForestClassifier(n_estimators=50)
model4.fit(X_train_bow,y_train)
y_pred= model4.predict(X_test_bow)

In [28]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9721973094170404

Classification Report:
               precision    recall  f1-score   support

         ham       0.97      1.00      0.98       965
        spam       1.00      0.79      0.88       150

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115


Confusion Matrix:
 [[965   0]
 [ 31 119]]